#!/usr/bin/env bash

# Uses git-subrepo branch "issue/142"

if [ -z "$1" ];
  then
    echo "overleaf git link not supplied";
    exit 1;
else
	mkdir .overleaf
	echo ".overleaf" >> .gitignore
	mv manuscript .overleaf
	git add .
	git commit -m "first"                                       # 1st commit
	git subrepo clone "$1" manuscript                           # 2nd commit
	mv manuscript/.gitrepo .overleaf/manuscript/.gitrepo
	rm -rf manuscript
	mv .overleaf/manuscript/ .
	git add .
	git commit -m "second"                                      # 3rd commit
	git reset --soft HEAD~3
	git commit -m "added manuscript subrepo to overleaf"
	echo "trying to push to manuscript to overleaf..."
	git subrepo push manuscript/
	echo "done"
fi
